version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: email_assistant
    ports:
      - "5432:5432"
    restart: unless-stopped